swagger: '2.0'
info:
  version: "1.1"
  title: 'LBH Income API'
  description: 'The Income API is the back-end of Hackney Income Collection Service'
paths:
  /actions:
    get:
      summary: 'Retrieve a list of actions'
      description: Returns a filtered list of actions for a worktray
      produces:
        - application/json
      parameters:
        - in: query
          name: service_area
          type: string
          description: This is a required parameter that detemines whenever you get leasehold actions or rent actions
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/actionList'
        400:
          description: Invalid search parameter
        404:
          description: Agreement not found
      tags:
        - actions
  /agreements/{tenancy_ref}:
    get:
      summary: 'Find agreements by tenancy id'
      description: Returns agreements with specified tenancy id
      operationId: getAgreementsByTenancyId
      produces:
        - application/json
      parameters:
        - in: path
          name: tenancy_ref
          required: true
          type: string
          description: tenancy Id record to retrieve
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/agreementsList'
        400:
          description: Invalid search parameter
        404:
          description: Action list not found
      tags:
        - agreements
  /agreement/{tenancy_ref}:
    post:
      summary: 'Create an agreement for the tenancy id'
      description: Create agreement with specified tenancy id
      operationId: postAgreementForTenancy
      produces:
        - application/json
      parameters:
        - in: path
          name: tenancy_ref
          required: true
          type: string
          description: Agreement for tenancy
        - in: body
          name: request_body
          description: Agreement params
          schema:
            type: object
            required: 
            - agreementType
            - startingBalance
            - amount
            - startDate
            - frequency
            - createdBy
            properties:
              agreementType:
                type: string
                example: 'informal'
              startingBalance:
                type: number
                example: '1000'
              initialPaymentAmount:
                type: number
                example: '100'
              initialPaymentDate:
                type: string
                format: date
              amount:
                type: number
                example: '50'
              startDate:
                type: string
                format: date
              frequency:
                type: string
                example: 'weekly'
              createdBy:
                type: string
                example: 'Joe Bloggs'
              notes:
                type: string
                example: 'When Chuck Norris presses Ctrl+Alt+Delete, worldwide computer restart is initiated.'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/agreement'
        400:
          description: Invalid search parameter
        404:
          description: Agreement not found
      tags:
        - agreements
  /agreements/{agreement_id}/cancel:
    post:
      summary: 'Cancel an agreement with id'
      description: Cancel agreement with specified id
      operationId: cancelAgreement
      produces:
        - application/json
      parameters:
        - in: path
          name: agreement_id
          required: true
          type: string
          description: Id of an agreement
        - in: body
          name: request_body
          required: true
          schema: 
            $ref: '#/definitions/cancel_agreement_body'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/agreement'
        400:
          description: Invalid search parameter
        404:
          description: Agreement not found
      tags:
        - agreements
  /court_cases/{tenancy_ref}:
    get:
      summary: 'Find court cases by tenancy id'
      description: Returns court cases with specified tenancy id
      operationId: getCourtCasesByTenancyId
      produces:
        - application/json
      parameters:
        - in: path
          name: tenancy_ref
          required: true
          type: string
          description: tenancy Id record to retrieve
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/courtCasesList'
        400:
          description: Invalid search parameter
        404:
          description: Court cases not found
      tags:
        - court_cases
  /court_case/{tenancy_ref}:
    post:
      summary: 'Create a court case for the tenancy id'
      description: Create court case with specified tenancy id
      operationId: postCourtCaseForTenancy
      produces:
        - application/json
      parameters:
        - in: path
          name: tenancy_ref
          required: true
          type: string
          description: Court case for tenancy
        - in: body
          name: court_case
          description: Court case to create
          schema:
            type: object
            required:
              - courtDate
              - createdBy
            properties:
              courtDate:
                type: string
                example: '01/08/2020'
              courtOutcome:
                type: string
                example: 'Stay of execution'
              balanceOnCourtOutcomeDate:
                type: number
                example: '50'
              strikeOutDate:
                type: string
                format: date
                example: '01/08/2026'
              createdBy:
                type: string
                example: 'Tom Nook'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/court_case'
        400:
          description: Invalid search parameter
        404:
          description: Court case not found
      tags:
        - court_cases


  /evictions/{tenancy_ref}:
    get:
      summary: 'Find evictions by tenancy id'
      description: Returns evictions with specified tenancy id
      operationId: getEvictionsForTenancy
      produces:
        - application/json
      parameters:
        - in: path
          name: tenancy_ref
          required: true
          type: string
          description: Eviction for tenancy
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/evictionList'
        400:
          description: Invalid search parameter
        404:
          description: Evictions not found
      tags:
        - evictions

  /eviction/{tenancy_ref}:
    post:
      summary: 'Create a eviction for the tenancy id'
      description: Create eviction with specified tenancy id
      operationId: postEvictionForTenancy
      produces:
        - application/json
      parameters:
        - in: path
          name: tenancy_ref
          required: true
          type: string
          description: Eviction for tenancy
        - in: body
          name: eviction
          description: Eviction to create
          schema:
            type: object
            required:
              - eviction
            properties:
              date:
                type: string
                example: '01/08/2020'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/eviction'
        400:
          description: Invalid search parameter
        404:
          description: Eviction not found
      tags:
        - evictions

definitions:
  agreementsList:
    type: object
    properties:
      agreements:
        type: array
        items:
          $ref: '#/definitions/agreement'
  agreement:
    type: object
    properties:
      id:
        type: integer
        example: 12
      tenancyRef:
        type: string
        example: '1'
      agreementType:
        type: string
        example: 'informal'
      startingBalance:
        type: number
        example: '1000'
      initialPaymentAmount:
        type: number
        example: '100'
      initialPaymentDate:
        type: string
        format: date
      amount:
        type: number
        example: '50'
      startDate:
        type: string
        format: date
      frequency:
        type: string
        example: 'weekly'
      currentState:
        type: string
        example: 'live'
      createdBy:
        type: string
        example: 'Joe Bloggs'
      createdAt:
        type: string
        format: date
      lastChecked:
        type: string
        format: date
      notes:
        type: string
        example: 'When Chuck Norris presses Ctrl+Alt+Delete, worldwide computer restart is initiated.'
      history:
        type: array
        items:
          $ref: '#/definitions/history'
  history:
    type: object
    properties:
      state:
        type: string
        example: 'live'
      date:
        type: string
        format: date
      checkedBalance:
        type: number
        example: '1000'
      expectedBalance:
        type: number
        example: '1000'
      description:
        type: string
        example: 'Agreement created'
  cancel_agreement_body:
    type: object
    properties:
      cancelled_by:
        type: string
        example: 'Joe Bloggs'
      cancellation_reason:
        type: string
        example: 'New agreement created'
  court_case:
    type: object
    properties:
      id:
        type: integer
        example: 12
      tenancyRef:
        type: string
        example: '1'
      courtDate:
        type: string
        format: date
        example: '01/08/2020'
      courtOutcome:
        type: string
        example: 'something'
      balanceOnCourtOutcomeDate:
        type: number
        format: '50'
      strikeOutDate:
        type: string
        format: date
        example: '01/08/2026'
      courtCaseHistory:
        type: array
        items:
          $ref: '#/definitions/courtCaseHistory'
  courtCaseHistory:
    type: object
    properties:
      description:
        type: string
        example: 'court date added'
      date:
        type: string
        format: date
        example: '01/07/2020'
      createdBy:
        type: string
        example: 'Tom Nook'
  courtCasesList:
    type: object
    properties:
      courtCases:
        type: array
        items:
          $ref: '#/definitions/court_case'

  action:
    type: object
    properties:
      id:
        type: integer
        example: 12
      tenancyRef:
        type: string
        example: '123456/01'
      paymentRef:
        type: string
        example: '1234567890'
      balance:
        type: number
        example: '123.53'
      patchCode:
        type: string
        example: 'W02'
      classification:
        type: string
        example: 'send_letter_one'
      pauseReason:
        type: string
        example: 'Waiting for payment'
      pauseComment:
        type: string
        example: 'Spoke to customer, they have agreed make a payment next week'
      pauseUntil:
        format: date
        example: '10/11/2020'
      actionType:
        type: string
        example: 'Freehold'
      serviceAreaType:
        type: string
        example: 'Leasehold'
      metadata:
        type: object
        properties:
          property_address:
            type: string
            example: '1 Hillman St, Hackney, London E8 1DY'
          lessee:
            type: string
            example: 'John Davis'
          tenure_type:
            type: string
            example: 'Freehold'
          direct_debit_status:
            type: string
            example: 'Live'
          latest_letter:
            type: string
            example: 'LF1'
          latest_letter_date:
            type: string
            example: '03/08/2020'

  actionList:
    type: object
    properties:
      actions:
        type: array
        items:
          $ref: '#/definitions/action'
  eviction:
    type: object
    properties:
      id:
        type: integer
        example: 12
      tenancyRef:
        type: string
        example: '1'
      date:
        type: string
        format: date
        example: '01/08/2020'
  evictionList:
    type: object
    properties:
      evictions:
        type: array
        items:
          $ref: '#/definitions/eviction'
schemes:
  - https
