swagger: '2.0'
info:
  version: "1.1"
  title: 'LBH Income API'
  description: 'The Income API is the back-end of Hackney Income Collection Service'
paths:
  /agreements/{tenancy_ref}:
    get:
      summary: 'Find agreements by tenancy id'
      description: Returns agreements with specified tenancy id
      operationId: getAgreementsByTenancyId
      produces:
      - application/json
      parameters:
      - in: path
        name: tenancy_ref
        required: true
        type: string
        description: tenancy Id record to retrieve
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/agreementsList'
        400:
          description: Invalid search parameter
        404:
          description: Agreement not found
      tags:
        - agreements
  /agreement/{tenancy_ref}:
    post:
      summary: 'Create an agreement for the tenancy id'
      description: Create agreement with specified tenancy id
      operationId: postAgreementForTenancy
      produces:
      - application/json
      parameters:
      - in: path
        name: tenancy_ref
        required: true
        type: string
        description: Agreement for tenancy
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/agreement'
        400:
          description: Invalid search parameter
        404:
          description: Agreement not found
      tags:
        - agreements
  /agreements/{agreement_id}/cancel:
    post:
      summary: 'Cancel an agreement with id'
      description: Cancel agreement with specified id
      operationId: cancelAgreement
      produces:
      - application/json
      parameters:
      - in: path
        name: agreement_id
        required: true
        type: string
        description: Id of an agreement
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/agreement'
        400:
          description: Invalid search parameter
        404:
          description: Agreement not found
      tags:
        - agreements
  /court_cases/{tenancy_ref}:
    get:
      summary: 'Find court cases by tenancy id'
      description: Returns court cases with specified tenancy id
      operationId: getCourtCasesByTenancyId
      produces:
      - application/json
      parameters:
      - in: path
        name: tenancy_ref
        required: true
        type: string
        description: tenancy Id record to retrieve
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/courtCasesList'
        400:
          description: Invalid search parameter
        404:
          description: Court cases not found
      tags:
        - court_cases
  /court_case/{tenancy_ref}:
    post:
      summary: 'Create a court case for the tenancy id'
      description: Create court case with specified tenancy id
      operationId: postCourtCaseForTenancy
      produces:
      - application/json
      parameters:
      - in: path
        name: tenancy_ref
        required: true
        type: string
        description: Court case for tenancy
      - in: body
        name: court_case
        description: Court case to create
        schema:
          type: object
          required:
            - courtDate
            - createdBy
          properties:
            courtDate:
              type: string
              example: '01/08/2020'
            courtOutcome:
              type: string
              example: 'Stay of execution'
            balanceOnCourtOutcomeDate:
              type: number
              example: '50'
            strikeOutDate:
              type: string
              format: date
              example: '01/08/2026'
            createdBy:
              type: string
              example: 'Tom Nook'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/court_case'
        400:
          description: Invalid search parameter
        404:
          description: Court case not found
      tags:
        - court_cases
definitions:
  agreementsList:
    type: object
    properties:
      agreements:
        type: array
        items:
          $ref: '#/definitions/agreement'
  agreement:
    type: object
    properties:
      id:
        type: integer
        example: 12
      tenancyRef:
        type: string
        example: '1'
      agreementType:
        type: string
        example: 'informal'
      startingBalance:
        type: number
        example: '1000'
      amount:
        type: number
        example: '50'
      startDate:
        type: string
        format: date
      frequency:
        type: string
        example: 'weekly'
      currentState:
        type: string
        example: 'live'
      createdBy:
        type: string
        example: 'Joe Bloggs'
      createdAt:
        type: string
        format: date
      courtCaseId:
        type: integer
        example: 12
      notes:
        type: string
        example: 'When Chuck Norris presses Ctrl+Alt+Delete, worldwide computer restart is initiated.'
      history:
        type: array
        items:
          $ref: '#/definitions/history'
  history:
    type: object
    properties:
      state:
        type: string
        example: 'breached'
      date:
        type: string
        format: date
  court_case:
    type: object
    properties:
      id:
        type: integer
        example: 12
      tenancyRef:
        type: string
        example: '1'
      courtDate:
        type: string
        format: date
        example: '01/08/2020'
      courtOutcome:
        type: string
        example: 'something'
      balanceOnCourtOutcomeDate:
        type: number
        format: '50'
      strikeOutDate:
        type: string
        format: date
        example: '01/08/2026'
      courtCaseHistory:
        type: array
        items:
          $ref: '#/definitions/courtCaseHistory'
  courtCaseHistory:
    type: object
    properties:
      description:
        type: string
        example: 'court date added'
      date:
        type: string
        format: date
        example: '01/07/2020'
      createdBy:
        type: string
        example: 'Tom Nook'
  courtCasesList:
    type: object
    properties:
      courtCases:
        type: array
        items:
          $ref: '#/definitions/court_case'
schemes:
 - https
