version: '3.1'
services:
  app:
    build:
      context: .
      args:
        SHELL_UID: "${SHELL_UID}"
    user: "${SHELL_UID}:${SHELL_UID}"
    environment:
      - UH_DATABASE_NAME=uhsimulator
      - UH_DATABASE_USERNAME=sa
      - UH_DATABASE_PASSWORD=Rooty-Tooty
      - UH_DATABASE_HOST=universal_housing_simulator
      - UH_DATABASE_PORT=1433
      - REDIS_URL=redis://redis:6379
      - AWS_REGION=eu-west-2
      - CUSTOMER_MANAGED_KEY=${CUSTOMER_MANAGED_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - GOV_NOTIFY_API_KEY=${GOV_NOTIFY_API_KEY}
    ports:
      - 3000:3000
    links:
      - universal_housing_simulator
    volumes:
      - .:/app
    command: sh -c 'rails db:migrate && rails s'
  universal_housing_simulator:
    image: 775052747630.dkr.ecr.eu-west-2.amazonaws.com/hackney/universal-housing-simulator:9855e4d527519516e8138a026e900ae26b4be5f3
    ports:
      - 1433:1433

  redis:
    image: redis:5.0.3-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - 6379:6379
