version: '3.1'
services:
  app:
    build: .
    environment:
      - UH_DATABASE_NAME=uhsimulator
      - UH_DATABASE_USERNAME=sa
      - UH_DATABASE_PASSWORD=Rooty-Tooty
      - UH_DATABASE_HOST=universal_housing
      - UH_DATABASE_PORT=1433
    ports:
      - 3000:3000
    links:
      - universal_housing
    volumes:
      - .:/app
  universal_housing:
    image: 775052747630.dkr.ecr.eu-west-2.amazonaws.com/hackney/universal-housing-simulator:latest
    ports:
      - 1433:1433
