version: '3.1'
services:
  app:
    build: .
    environment:
      - UH_DATABASE_NAME=uhsimulator
      - UH_DATABASE_USERNAME=sa
      - UH_DATABASE_PASSWORD=Rooty-Tooty
      - UH_DATABASE_HOST=universal_housing_simulator
      - UH_DATABASE_PORT=1433
      - GOV_NOTIFY_API_KEY='tempmarktest-c0623e2d-7536-4476-9060-18864bca6b20-5739f5c8-78ae-4709-967c-ae76e49d0754'
    ports:
      - 3000:3000
    links:
      - universal_housing_simulator
    volumes:
      - .:/app
    command: sh -c 'rails db:migrate && rails s'
  universal_housing_simulator:
    image: 775052747630.dkr.ecr.eu-west-2.amazonaws.com/hackney/universal-housing-simulator:140ad3ef65f4a44d8bbbb3add55968a157625647
    ports:
      - 1433:1433
