version: 2
jobs:
  check:
    machine: true
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user
      - run:
          name: Login to ECR
          command: aws ecr get-login --region $AWS_REGION --no-include-email | sh
      - run:
          name: Build projects
          command: docker-compose build
      - run:
          name: Spin up docker instances
          command: docker-compose up -d ; sleep 20
      - run:
          name: Run tests
          command: docker-compose exec app rspec

  staging_release:
    machine: true
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user
      - run:
          name: Install jq
          command: |
            sudo apt-get update
            sudo apt-get install jq
      - run:
          name: Install ecs-deploy
          command: |
            curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
            sudo chmod +x /usr/bin/ecs-deploy
      - run:
          name: Login to ECR
          command: aws ecr get-login --region $AWS_REGION --no-include-email | sh
      - run:
          name: Build new application Docker image
          command: docker build --tag hackney/apps/income-api .
      - run:
          name: Tag new image for staging release
          command: |
            docker tag hackney/apps/income-api:latest $ECR_IMAGE_URL:$CIRCLE_SHA1
            docker tag hackney/apps/income-api:latest $ECR_IMAGE_URL:latest
            docker tag hackney/apps/income-api:latest $ECR_IMAGE_URL:staging
      - run:
          name: Release new image to ECR
          command: |
            docker push $ECR_IMAGE_URL:$CIRCLE_SHA1
            docker push $ECR_IMAGE_URL:latest
            docker push $ECR_IMAGE_URL:staging
      - run:
          name: Force new deployment
          command: ecs-deploy --region $AWS_REGION --cluster $ECS_STAGING_CLUSTER --service-name $ECS_STAGING_APP_NAME --image $ECR_IMAGE_URL:staging --timeout 1800

workflows:
  version: 2
  continuous_delivery:
    jobs:
      - check
      - staging_release:
          requires:
            - check
          # filters:
          #   branches:
          #     only: master
