development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV.fetch("DATABASE_NAME") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
test:
  adapter: mysql2
  encoding: utf8
  database: app-database-<%= ENV.fetch("RAILS_ENV") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: bar
  host: incomeapi-db

  # staging and production should be injected via DATABASE_URL
