# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 987b910d694d082666ab3e67f9ae0da69d4fd3a9591aa34b436e87143b3fe734113d70a54655e708ecdb1a628e376ede7097f264d115c703ccab924f176e266b

test:
  secret_key_base: 84da4baf6734bfd2d8c35fb27ea2a1728e44d5db1be37acb8aac17da2f86fe7e444cc05350418f1f277920eb98d501714a6e74d70114d1f2465f07a37a105cfe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
